version: '3.6'

volumes:
  dbdata:

services:
  db:
    image: postgis/postgis:11-3.3-alpine
    restart: always
    # To preserve data between runs of docker-compose, we mount a folder from the host machine.
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
