name: Run Rspec, Rubocop, and Brakeman

on: [push]

env:
  RAILS_ENV: test
  GOOGLE_MAP_API_KEY: notusedinspecs
  SECRET_KEY_BASE: notusedinspecs

jobs:
  rspec:
    name: Run Rspec

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:11-3.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Install dependencies
        run: sudo apt-get install -y libproj-dev proj-bin

      - name: Set up ruby gem cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install yarn
        run: npm install yarn -g

      - name: Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set up yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node.js dependencies
        run: yarn install

      - name: Set up test database
        run: bin/rails db:create db:schema:load
        env:
          DATABASE_URL: postgis://postgres:password@localhost:5432/test

      - name: Run tests
        run: bundle exec rake
        env:
          DATABASE_URL: postgis://postgres:password@localhost:5432/test
  linting:
    name: Run Rubocop

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.0'

      - name: Set up ruby gem cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: sudo apt-get install -y libproj-dev proj-bin

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install node.js dependencies
        run: yarn install

      - name: Run rubocop
        run: bundle exec rubocop --format clang --parallel

#  brakeman:
#    name: Run Brakeman
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.1.2
#
#      - name: Set up Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: '16.20.0'
#
#      - name: Set up ruby gem cache
#        uses: actions/cache@v3
#        with:
#          path: vendor/bundle
#          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-gems-
#
#      - name: Install dependencies
#        run: sudo apt-get install -y libproj-dev proj-bin
#
#      - name: Install gems
#        run: |
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3
#
#      - name: Run brakeman
#        run: bundle exec brakeman
